image: node:14.15-alpine

variables:
  APP_VERSION: "0.0.1"

stages:
  - build
  - test
  - deploy


node-build:
  stage: build
  script:
    - npm install
  artifacts:
    expire_in: 1h
    paths:
      - node_modules


unit-test:
  stage: test
  script:
    - npm run test


inspect-sonar-feedback:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - dev
    - staging
    - merge_requests


pages:
  stage: deploy
  before_script:
    - npm ci
    - cat $ENV_FILE > .env
  script:
    - npm run build
    - mv public public-vue
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
